# Generated by Django 3.2.15 on 2022-10-06 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_alter_contentpage_body_optional_ctablocks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signupformsnippet',
            name='mailchimp_newsletter_id',
            field=models.CharField(blank=True, max_length=255, verbose_name='Mailchimp Audience ID'),
        ),
    ]
